// ===== Theme toggle =====
(function themeInit() {
  const root = document.documentElement;
  const saved = localStorage.getItem('icons-placement-theme');
  if (saved) root.setAttribute('data-theme', saved);
  const btn = document.getElementById('themeToggleBtn');
  if (btn) {
    btn.addEventListener('click', () => {
      const next = root.getAttribute('data-theme') === 'light' ? 'dark' : 'light';
      root.setAttribute('data-theme', next);
      localStorage.setItem('icons-placement-theme', next);
    });
  }
})();

// ===== Mobile nav toggle =====
(function navInit() {
  const toggle = document.getElementById('navToggle');
  const links = document.getElementById('navLinks');
  if (toggle && links) {
    toggle.addEventListener('click', () => links.classList.toggle('open'));
    links.querySelectorAll('a').forEach(a => a.addEventListener('click', () => links.classList.remove('open')));
  }
})();

// ===== Active nav link highlight =====
(function activeNavInit() {
  const path = location.pathname.split('/').pop() || 'index.html';
  document.querySelectorAll('.nav-links a[data-page]').forEach(a => {
    if (a.dataset.page === path) a.classList.add('active');
  });
})();

// ===== Scroll reveal =====
(function revealInit() {
  const items = document.querySelectorAll('.reveal');
  if (!items.length) return;
  const io = new IntersectionObserver((entries) => {
    entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('in-view'); io.unobserve(e.target); } });
  }, { threshold: 0.15 });
  items.forEach(el => io.observe(el));
})();

// ===== Accordion (aptitude topics) =====
(function accordionInit() {
  document.querySelectorAll('.acc-head').forEach(head => {
    head.addEventListener('click', () => {
      const item = head.closest('.acc-item');
      item.classList.toggle('open');
    });
  });
})();

// ===== Reveal answer (Q&A cards) =====
(function qaRevealInit() {
  document.querySelectorAll('.qa-reveal-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      const answer = btn.closest('.qa-card').querySelector('.qa-answer');
      const open = answer.classList.toggle('open');
      btn.textContent = open ? 'Hide Answer' : 'Show Answer';
    });
  });
})();

// ===== Company folders (auto-synced from Google Drive) =====
// HOW THIS WORKS — read this before editing anything below:
// Each department page has a container like:
//   <div class="grid cols-4" data-drive-folder="FOLDER_ID"></div>
// where FOLDER_ID is that department's "Companies" folder in Google Drive.
// On page load, this script asks Google Drive what subfolders are inside that
// folder and turns each one into a clickable button automatically.
//
// TO ADD, RENAME, OR REMOVE A COMPANY: do it inside the Google Drive folder.
// Do NOT edit this file or the department HTML — the buttons update themselves.
// Folders named "Copy of ..." (Drive's auto-name for a duplicate) are skipped.
//
// ONE-TIME SETUP: paste a Google Drive API key below. Get one at
// https://console.cloud.google.com -> APIs & Services -> Credentials -> Create API Key,
// then restrict it to the "Google Drive API" and to this website's domain.
const DRIVE_API_KEY = 'PASTE_DRIVE_API_KEY_HERE';

(function companyFoldersInit() {
  const containers = document.querySelectorAll('[data-drive-folder]');
  if (!containers.length) return;

  containers.forEach(async (container) => {
    const folderId = container.dataset.driveFolder;
    const keyMissing = !DRIVE_API_KEY || DRIVE_API_KEY === 'PASTE_DRIVE_API_KEY_HERE';
    if (keyMissing || !folderId) {
      container.textContent = 'Company list is not set up yet.';
      return;
    }

    const params = new URLSearchParams({
      q: `'${folderId}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false`,
      orderBy: 'name',
      fields: 'files(id,name)',
      key: DRIVE_API_KEY
    });

    try {
      const res = await fetch(`https://www.googleapis.com/drive/v3/files?${params.toString()}`);
      if (!res.ok) throw new Error('Drive API request failed');
      const data = await res.json();
      const folders = (data.files || []).filter(f => !/^copy of/i.test(f.name.trim()));

      container.innerHTML = '';
      if (!folders.length) {
        container.textContent = 'No companies listed yet.';
        return;
      }
      folders.forEach(f => {
        const a = document.createElement('a');
        a.href = `https://drive.google.com/drive/folders/${f.id}`;
        a.target = '_blank';
        a.rel = 'noopener';
        a.className = 'company-pill';
        a.textContent = f.name;
        container.appendChild(a);
      });
    } catch (err) {
      container.innerHTML = '';
      const p = document.createElement('p');
      p.className = 'section-sub';
      p.textContent = "Couldn't load the company list. ";
      const a = document.createElement('a');
      a.href = `https://drive.google.com/drive/folders/${folderId}`;
      a.target = '_blank';
      a.rel = 'noopener';
      a.textContent = 'Open the Drive folder directly →';
      p.appendChild(a);
      container.appendChild(p);
    }
  });
})();

// ===== Stat number count-up animation =====
(function statCountInit() {
  const cards = document.querySelectorAll('.stat-card');
  if (!cards.length) return;

  function animateCount(el) {
    const target = parseFloat(el.dataset.target);
    if (Number.isNaN(target)) return;
    const decimals = el.dataset.decimals ? parseInt(el.dataset.decimals, 10) : 0;
    const duration = 1200;
    const start = performance.now();
    function tick(now) {
      const progress = Math.min((now - start) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      el.textContent = (target * eased).toFixed(decimals);
      if (progress < 1) requestAnimationFrame(tick);
      else el.textContent = target.toFixed(decimals);
    }
    requestAnimationFrame(tick);
  }

  const io = new IntersectionObserver((entries) => {
    entries.forEach(e => {
      if (e.isIntersecting) {
        e.target.querySelectorAll('.count').forEach(animateCount);
        io.unobserve(e.target);
      }
    });
  }, { threshold: 0.4 });
  cards.forEach(c => io.observe(c));
})();

// ===== Resource filters =====
(function filterInit() {
  const buttons = document.querySelectorAll('.filter-btn');
  const cards = document.querySelectorAll('.resource-card');
  if (!buttons.length) return;
  buttons.forEach(btn => {
    btn.addEventListener('click', () => {
      buttons.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      const cat = btn.dataset.filter;
      cards.forEach(card => {
        card.classList.toggle('hidden', cat !== 'all' && card.dataset.cat !== cat);
      });
    });
  });
})();
